let actions_const = {
  "GET_STUDENTS": "getStudents",
  "GET_LOGIN_MEMBER": "getLoginMember",
  'GET_CLASS_TEACHING_ASSISTANT':'getClassTeachingAssistant'
};
let mutations_const = {
  "RESET_STUDENTS":"RESET_STUDENTS",
  "UPDATE_LOGIN_MEMBER":"UPDATE_LOGIN_MEMBER",
  "UPD_HEIGHT":"UPD_HEIGHT" ,
  "UPD_WIDTH":"UPD_WIDTH",
  "UPD_BLE_STATE":"UPD_BLE_STATE",
  'UPD_ROUTE':'UPD_ROUTE',
  'UPD_FIRST_PAGE':'UPD_FIRST_PAGE',
  "RESET_LOGIN_MEMBER":"RESET_LOGIN_MEMBER",
  'UPDATE_CLASS_TEACHING_ASSISTANT':'UPDATE_CLASS_TEACHING_ASSISTANT'
};
export
{
  actions_const,
  mutations_const
}
